debugOpt =
include = .;c:\watcom\h

target = sc.exe

objects =  &
 new.obj &
 getargs.obj &
 string.obj &
 fileio.obj &
 alist.obj &
 anode.obj &
 asm.obj &
 banner.obj &
 builtins.obj &
 chartype.obj &
 class.obj &
 compile.obj &
 define.obj &
 error.obj &
 expr.obj &
 input.obj &
 list.obj &
 listing.obj &
 loop.obj &
 mem.obj &
 object.obj &
 optimize.obj &
 output.obj &
 parse.obj &
 pnode.obj &
 proc.obj &
 resource.obj &
 selector.obj &
 share.obj &
 symbol.obj &
 symtbl.obj &
 text.obj &
 token.obj &
 toktypes.obj &
 update.obj &
 sc.obj 

$(target) : $(objects)
	*wlink &
	system nt &
	name $(target) &
	debug all file {$<} &
	option map

#	system dos4g &
#	option stack=10000 &
