name: Build For Platforms
on:
  push:
    paths-ignore:
      - 'site/**'
jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.13.0
              with:
                # Avoid downloading Bazel every time.
                bazelisk-cache: true
                # Store build cache per workflow.
                disk-cache: ${{ github.workflow }}
                # Share repository cache between workflows.
                repository-cache: true
            - name: Build for macOS
              run: bazel test //...
    build-linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.13.0
              with:
                bazelisk-cache: true
                disk-cache: ${{ github.workflow }}
                repository-cache: true
            - name: Build for Linux
              run: bazel test //...
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: bazel-contrib/setup-bazel@0.13.0
              with:
                bazelisk-cache: true
                disk-cache: ${{ github.workflow }}
                repository-cache: true
            - name: Build for Windows
              run: bazel test //...
            